apiVersion: gaudi.resource.intel.com/v1alpha1
kind: GaudiClaimParameters
metadata:
  name: delayed-pod-inline-gaudi
  namespace: default
spec:
  count: 1
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: delayed-pod-inline-gaudi
  namespace: default
spec:
  metadata:
    labels:
      app: delayed-pod-inline-gaudi
  spec:
    resourceClassName: intel-gaudi
    parametersRef:
      apiGroup: gaudi.resource.intel.com/v1alpha1
      kind: GaudiClaimParameters
      name: delayed-pod-inline-gaudi
---
apiVersion: v1
kind: Pod
metadata:
  name: delayed-pod-inline-gaudi
spec:
  restartPolicy: Never
  containers:
  - name: with-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "ls -la /dev/dri/ && sleep 5"]
    resources:
      claims:
      - name: resource
  - name: without-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "ls -la /dev/ && sleep 5"]
  resourceClaims:
  - name: resource
    source:
      resourceClaimTemplateName: delayed-pod-inline-gaudi
