apiVersion: v1
kind: Deployment
metadata:
  name: qat-sample-sym
  labels:
    app: inline-qat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inline-qat-deployment
  template:
    metadata:
      labels:
        app: inline-qat-deployment
    spec:
      containers:
      - name: with-resource
        image: registry.k8s.io/e2e-test-images/busybox:1.29-2
        command: ["sh", "-c", "ls -la /dev/vfio/ && sleep 300"]
        securityContext:
          capabilities:
            add:
              ["IPC_LOCK"]
        resources:
          claims:
          - name: resource-sym-asym
          - name: resource-dc
      - name: without-resource
        image: registry.k8s.io/e2e-test-images/busybox:1.29-2
        command: ["sh", "-c", "ls -la /dev/ && sleep 300"]
      resourceClaims:
      - name: resource-sym-asym
        resourceClaimTemplateName: qat-template-sym
      - name: resource-dc
        resourceClaimTemplateName: qat-template-dc
