# Copyright (c) 2024, Intel Corporation.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.23.4-bookworm@sha256:2e838582004fab0931693a3a84743ceccfbfeeafa8187e87291a1afea457ff7a as build
ARG LOCAL_LICENSES
WORKDIR /build
COPY . .
# TODO: get official libhlml.so
COPY ./habanalabs /usr/lib/habanalabs

RUN make gaudi && \
mkdir -p /install_root && \
if [ -z "$LOCAL_LICENSES" ]; then \
    make licenses; \
fi && \
cp -r licenses /install_root/ && \
cp bin/kubelet-gaudi-plugin /install_root/

# TODO: use slim, copy libhlml.so from build image
# # Use one of base:
FROM debian:bookworm
# # or
#FROM scratch
#WORKDIR /

LABEL description="Intel Gaudi resource driver for Kubernetes"

COPY --from=build /install_root /
#COPY --from=build /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6
COPY ./habanalabs /usr/lib/