name: Build all targets

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: [self-hosted, generic]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: create symlink for xpum code
        run: |
          ln -s ~/xpum ./xpumanager
      - name: Build
        run: make build
