name: GPU E2E Run

on:
  schedule:
    # 05:00 every Monday
    - cron: "0 5 * * 0"

permissions:
  contents: read
  pull-requests: read

jobs:
  e2e:
    needs: "setup-system"
    runs-on: [ "self-hosted", "kubernetes-gpu-ci" ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create K8s cluster
      run: ./.github/gpu-scripts/create_cluster.sh
    - name: Describe test environment
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Actor: ${{ github.actor }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"
        echo "Images: $IMAGES"
        echo "Target job: $TARGET_JOB"
        echo "Cluster: $(kubectl version)"
        echo "Cluster state: $(kubectl get pods -A)"
    - name: Run E2E tests
      run: ./.github/gpu-scripts/run_e2e.sh
      env:
        GPU_IMAGE_TAG: "ger-is-registry.caas.intel.com/dgpu-orchestration/intel-gpu-resource-driver:devel"
    - name: Teardown test environment
      if: always()
      run: kind delete cluster

