name: Coral E2E Run

on:
 push:
   branches:
     - main
 pull_request:
   paths:
     - '**/*gpu*/**'
     - '**/*gpu*'

permissions:
  contents: read
  pull-requests: read

jobs:
  setup-coral-sim:
    runs-on: [ "self-hosted", "gpu-reserver" ]
    steps:
    - name: Setup system for e2e
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        $HOME/coral.kmd.setup.for.k8s/run_coral_and_setup_env.sh
  setup-actions-runner:
    needs: "setup-coral-sim"
    runs-on: [ "self-hosted", "gpu-reserver" ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup actions runner in coral simulator
      env:
        ACTIONS_RUNNER_NAME: coral
        LDAP_USERNAME: ${{ secrets.CI_USER_NAME }}
        LDAP_PASSWORD: ${{ secrets.CI_USER_PASS }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PROXY_URL: http://proxy-ir.intel.com:911
      run: |
          ACTIONS_RUNNER_NAME="${ACTIONS_RUNNER_NAME}"
          LDAP_USERNAME="${LDAP_USERNAME}"
          LDAP_PASSWORD="${LDAP_PASSWORD}"
          PROXY_URL="${PROXY_URL}"
          export ACTIONS_RUNNER_NAME LDAP_USERNAME LDAP_PASSWORD PROXY_URL
          bash .github/gpu-scripts/setup_actions_runner.sh
  e2e:
    needs: "setup-actions-runner"
    runs-on: [ "self-hosted", "coral" ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      run: .github/gpu-scripts/install_go.sh
    - name: Run E2E tests
      run: |
          source /etc/environment
          ./.github/gpu-scripts/run_e2e.sh
  destroy-coral-sim:
    needs: e2e
    runs-on: [ "self-hosted", "gpu-reserver" ]
    steps:
    - name: Destroy HVT VM
      run: |
        ssh 811643.intel.com ".hvt/hvt vm destroy"
