name: QAT E2E Run

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    paths:
#      - '**/*qat*/**'
#      - '**/*qat*'

permissions:
  contents: read
  pull-requests: read

jobs:
  reserve-onecloud:
    runs-on: [ "self-hosted", "reserver" ]
    steps:
      - name: Reserve OneCloud System for E2E
        env:
          CI_USER_ONECLOUD_TOKEN : ${{ secrets.CI_USER_ONECLOUD_TOKEN }}
        run: ../../../jobs/reserve_onecloud.sh
  setup-system:
    needs: "reserve-onecloud"
    runs-on: [ "self-hosted", "reserver" ]
    steps:
      - name: Setup the System for E2E
        env:
          ACTIONS_RUNNER_NAME: qat
          LDAP_USERNAME: ${{ secrets.CI_USER_NAME }}
          LDAP_PASSWORD: ${{ secrets.CI_USER_PASS }}
          CI_USER_ONECLOUD_TOKEN : ${{ secrets.CI_USER_ONECLOUD_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ../../../jobs/setup_actions_runner.sh
  e2e:
    needs: "setup-system"
    runs-on: [ "self-hosted", "qat" ]
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
    - name: Create a K8s Cluster
      run: ../../../../../jobs/qat_dra_driver/ssh_host_and_recreate_cluster.sh
    - name: Build an Image for the QAT Driver and Obtain Test Images
      run: ../../../../../jobs/qat_dra_driver/build.sh
    - name: Run E2E Tests
      run: ../../../../../jobs/qat_dra_driver/run_e2e.sh
  release-onecloud:
    needs: "e2e"
    runs-on: [ "self-hosted", "reserver" ]
    steps:
      - name: Release the OneCloud System
        env:
          CI_USER_ONECLOUD_TOKEN : ${{ secrets.CI_USER_ONECLOUD_TOKEN }}
        run: ../../../jobs/release_onecloud.sh
