name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build-test-image:
    runs-on: [ "self-hosted", "generic" ]
    steps:
    - uses: actions/checkout@v4
    - name: Build test image
      run: make test-image
  test:
    runs-on: [ "self-hosted", "generic" ]
    needs: build-test-image
    container:
      image: gaudi-test
    steps:
    - uses: actions/checkout@v4
    - name: Update vendor
      run: go mod vendor
    - name: Test
      run: make test
